[package]
name = "advent_of_code"
version = "0.11.0"
authors = ["Felix Spöttel <1682504+fspoettel@users.noreply.github.com>"]
edition = "2021"
default-run = "advent_of_code"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[profile.dhat]
inherits = "release"
debug = 1

[features]
dhat-heap = ["dhat"]
today = ["chrono"]
test_lib = []

[lints.rust]
unused = "allow"

[dependencies]

# Template dependencies
chrono = { version = "0.4.38", optional = true }
dhat = { version = "0.3.3", optional = true }
itertools = "0.14.0"
pathfinding = "4.13.1"
num-traits = "0.2.19"
pico-args = "0.5.0"
regex = "1.11.1"
tinyjson = "2.5.1"
once_cell = "1.20.2"
nom = "8.0.0"
hex = "0.4.3"
fxhash = "0.2.1"
bit-set = "0.8.0"

# Solution dependencies

